name: EGTools
author: iTrooz_
description: Utilités pour le EntaGames
version: 1.2.0
main: fr.entasia.egtools.Main
depend: [Libraries]
commands:
  egtools:
    aliases: [egtool]

  spawn:

  money:

  eco:
    aliases: [economy]

  buildtoggle:
    aliases: [bt]
